#pragma once

#include <emscripten.h>
#include <emscripten/bind.h>
#include <emscripten/webaudio.h>

#include <z_libpd.h>
#include <z_print_util.h>

#include "config.h"

#define PD4WEB_MAJOR_VERSION 2
#define PD4WEB_MINOR_VERSION 0
#define PD4WEB_MICRO_VERSION 0

#define PD4WEB_DEBUG true

void Pd4WebInitExternals(); // defined in externals.cpp (generated by pd4web.py)
static uint8_t wasmAudioWorkletStack[1024 * 1024];

// ╭─────────────────────────────────────╮
// │             Main Class              │
// ╰─────────────────────────────────────╯

class Pd4Web {
  public:
    static void AudioWorkletProcessorCreated(EMSCRIPTEN_WEBAUDIO_T audioContext, EM_BOOL success,
                                             void *userData);

    void Init();
    void SuspendAudio();
    void ResumeAudio();

    // bind symbols
    void BindReceiver(std::string s);
    void BindGuiReceiver(std::string s, std::string obj);
    void UnbindReceiver();

    // send Messages
    bool SendFloat(std::string r, float f);
    bool SendSymbol(std::string r, std::string s);
    bool SendBang(std::string r);

    bool _startMessage(int argc);
    void _addFloat(float f);
    void _addSymbol(std::string s);
    void _finishMessage(std::string s);

    // libpd HOOKs
    void receiveMessage(const char *source, const char *symbol, int argc, t_atom *argv);

  private:
    static int GetNInputChannels();
    static int GetNOutputChannels();
    static uint32_t GetSampleRate();

    // bind list

    bool m_Pd4WebInit = false;
    EMSCRIPTEN_WEBAUDIO_T m_Context;
    bool m_PdInit = false;
};

// ╭─────────────────────────────────────╮
// │  Bind C++ functions to JavaScript   │
// ╰─────────────────────────────────────╯
EMSCRIPTEN_BINDINGS(WebPd) {
    emscripten::class_<Pd4Web>("Pd4Web")
        .constructor<>() // Default constructor
        .function("init", &Pd4Web::Init)
        .function("suspendAudio", &Pd4Web::SuspendAudio)
        .function("resumeAudio", &Pd4Web::ResumeAudio)

        // senders
        .function("sendFloat", &Pd4Web::SendFloat)
        .function("sendSymbol", &Pd4Web::SendSymbol)
        .function("sendBang", &Pd4Web::SendBang)

        // sendList is added by _Pd4WebJSFunctions();
        .function("_startMessage", &Pd4Web::_startMessage)
        .function("_addFloat", &Pd4Web::_addFloat)
        .function("_addSymbol", &Pd4Web::_addSymbol)
        .function("_finishMessage", &Pd4Web::_finishMessage)

        // bind list
        .function("bindReceiver", &Pd4Web::BindReceiver)
        .function("bindGuiReceiver", &Pd4Web::BindGuiReceiver)
        .function("unbindReceiver", &Pd4Web::UnbindReceiver);
}
