# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/neimog/Documents/Git/pd4web/Documentation/tests/gui2;/home/neimog/Documents/Git/pd4web/Documentation/tests/gui2/.build")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/home/neimog/.config/miniconda3.dir/lib/python3.13/site-packages/pd4web/bin/cmake/share/cmake-4.2/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "else built using CMake")
set(CPACK_GENERATOR "TGZ")
set(CPACK_INNOSETUP_ARCHITECTURE "x86")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/neimog/Documents/Git/pd4web/Documentation/tests/gui2/.build;else;ALL;/")
set(CPACK_INSTALL_PREFIX "/home/neimog/.config/miniconda3.dir/lib/python3.13/site-packages/pd4web/emsdk/upstream/emscripten/cache/sysroot")
set(CPACK_MODULE_PATH "/home/neimog/.config/miniconda3.dir/lib/python3.13/site-packages/pd4web/emsdk/upstream/emscripten/cmake/Modules;/home/neimog/.config/miniconda3.dir/lib/python3.13/site-packages/pd4web/emsdk/upstream/emscripten/cmake/Modules;/home/neimog/Documents/Git/pd4web/Documentation/tests/gui2/Pd4Web/Externals/else/Source/Shared/opus/cmake")
set(CPACK_NSIS_DISPLAY_NAME "else 0.1.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "else 0.1.1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/neimog/Documents/Git/pd4web/Documentation/tests/gui2/.build/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/neimog/.config/miniconda3.dir/lib/python3.13/site-packages/pd4web/bin/cmake/share/cmake-4.2/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "else built using CMake")
set(CPACK_PACKAGE_FILE_NAME "else-0.1.1-Emscripten")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "else 0.1.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "else 0.1.1")
set(CPACK_PACKAGE_NAME "else")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "0.1.1")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/neimog/.config/miniconda3.dir/lib/python3.13/site-packages/pd4web/bin/cmake/share/cmake-4.2/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/home/neimog/.config/miniconda3.dir/lib/python3.13/site-packages/pd4web/bin/cmake/share/cmake-4.2/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/home/neimog/.config/miniconda3.dir/lib/python3.13/site-packages/pd4web/bin/cmake/share/cmake-4.2/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/neimog/Documents/Git/pd4web/Documentation/tests/gui2/.build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Emscripten")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Emscripten")
set(CPACK_WIX_SIZEOF_VOID_P "4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/neimog/Documents/Git/pd4web/Documentation/tests/gui2/.build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
