name: Pd4web Compiler

on:
  workflow_dispatch:
  push:
    branches: [main, dev]

jobs:
  pd4web-compiler:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest ]
        #, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build Object
        run: |
          cd Sources/Compiler
          cmake . -B build -DCMAKE_POLICY_DEFAULT_CMP0077=NEW -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - name: Upload Object (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: pd4web-${{ matrix.os }}
          path: ./Sources/Compiler/build/Release/pd4web.exe

      - name: Upload Object (Unix)
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: pd4web-${{ matrix.os }}
          path: ./Sources/Compiler/build/pd4web

