name: Pd4web Compiler

on:
  workflow_dispatch:

jobs:
  pd4web-compiler:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive
            fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Upgrade pip & install build backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      # ---------- Windows-specific toolchain fixes ----------
      - name: Install NASM (Windows)
        if: matrix.os == 'windows-latest'
        uses: ilammy/setup-nasm@v1

      - name: Install Perl & (optional) Ninja (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          choco install strawberryperl -y
          choco install ninja -y
          perl -v
          nasm -v
          ninja --version
          where nasm
          where perl
          where ninja

      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pd4web-whl-${{ matrix.os }}
          path: dist/*.whl
          if-no-files-found: error
