name: Pd4web Compiler

on:
  workflow_dispatch:
  push:
    branches: [main, dev]

jobs:
  pd4web-compiler:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Upgrade pip, install build
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Install nasm (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          choco install nasm
          echo "C:\Program Files\NASM" >> $GITHUB_PATH
          echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH
      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pd4web-whl-${{ matrix.os }}
          path: dist/*.whl
